apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hass-backup.fullname" . }}
  labels:
    {{- include "hass-backup.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "hass-backup.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ include "hass-backup.imageTag" . }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "hass-backup.fullname" . }}-secret
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
