apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hass-backup.fullname" . }}-secret
  labels:
    {{- include "hass-backup.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
